"use client";

import React from 'react';
import { useEffect, useState } from 'react';
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Skeleton } from "@/components/ui/skeleton";

export default function ReportViewPage() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("report");

  useEffect(() => {
    // Get report data from localStorage
    const reportData = localStorage.getItem('currentReport');
    if (reportData) {
      setReport(JSON.parse(reportData));
    }
    setLoading(false);
  }, []);

  if (loading) {
    return (
      <div className="container mx-auto py-8">
        <Skeleton className="h-12 w-3/4 mb-6" />
        <Skeleton className="h-8 w-1/2 mb-4" />
        <Skeleton className="h-64 w-full mb-6" />
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  if (!report) {
    return (
      <div className="container mx-auto py-8 text-center">
        <h1 className="text-3xl font-bold mb-6">No Report Found</h1>
        <p className="mb-6">No report data is available. Please generate a report first.</p>
        <Button onClick={() => window.location.href = '/reports/templates'}>
          Go to Report Templates
        </Button>
      </div>
    );
  }

  return (
    <div className="container mx-auto py-8">
      <h1 className="text-3xl font-bold mb-2">{report.title}</h1>
      <p className="text-muted-foreground mb-6">Report Type: {report.type.charAt(0).toUpperCase() + report.type.slice(1)}</p>
      
      <Tabs defaultValue="report" className="w-full" onValueChange={setActiveTab}>
        <TabsList className="grid grid-cols-3 mb-8">
          <TabsTrigger value="report">Report</TabsTrigger>
          <TabsTrigger value="insights">AI Insights</TabsTrigger>
          <TabsTrigger value="reasoning">AI Reasoning</TabsTrigger>
        </TabsList>
        
        <TabsContent value="report" className="space-y-6">
          <Card>
            <CardContent className="pt-6">
              {report.htmlContent ? (
                <div dangerouslySetInnerHTML={{ __html: report.htmlContent }} />
              ) : (
                <div className="text-center py-12">
                  <p>Report content is not available.</p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="insights" className="space-y-6">
          <Card>
            <CardContent className="pt-6">
              <h2 className="text-2xl font-bold mb-4">AI-Generated Insights</h2>
              <p className="mb-6">These insights were automatically generated by DeepSeek V3 based on your marketing data.</p>
              
              {report.insights ? (
                <div className="space-y-6">
                  {report.insights.map((insight, index) => (
                    <div key={index} className="border rounded-lg p-4">
                      <h3 className="text-lg font-bold mb-2">{insight.title}</h3>
                      <p className="mb-3">{insight.explanation}</p>
                      <div className="bg-muted p-3 rounded-md">
                        <h4 className="font-medium mb-1">Recommendation:</h4>
                        <p className="text-muted-foreground">{insight.recommendation}</p>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-12">
                  <p>No insights available for this report.</p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="reasoning" className="space-y-6">
          <Card>
            <CardContent className="pt-6">
              <h2 className="text-2xl font-bold mb-4">AI Reasoning Process</h2>
              <p className="mb-6">This shows the Chain of Thought (CoT) reasoning process used by DeepSeek V3 to generate this report.</p>
              
              {report.reasoning ? (
                <div className="bg-muted p-4 rounded-lg whitespace-pre-wrap font-mono text-sm">
                  {report.reasoning}
                </div>
              ) : (
                <div className="text-center py-12">
                  <p>Reasoning process is not available for this report.</p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
      
      <div className="mt-8 flex justify-between">
        <Button variant="outline" onClick={() => window.location.href = '/reports/templates'}>
          Back to Templates
        </Button>
        <Button onClick={() => window.print()}>
          Export Report
        </Button>
      </div>
    </div>
  );
}
